services:
  - type: web
    name: tic-tac-toe-backend
    env: node
    rootDir: .
    buildCommand: npm install
    startCommand: node server.js
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 20

